### ISSUE TITLE
plus de toons

### ISSUE THREAD

**Issue by jinformatique** [framasoft/geektionnerd-generator#4]
Bonjour,

Dans la version geektionnerd-generator à cette adresse :
https://framalab.org/gknd-creator/
il y a plus d'images (environ 30 toons au lieu de 11). Est-il prévu de mettre à jour ce dépot git pour bénéficier des nouveautés ?

Merci.

**Comment by tcitworld** [comment]
Le dépôt git devrait être à jour.
